version: '3.8'

services:
  digital-bloom-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    container_name: digital-bloom-test
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
